-- MySQL Script generated by MySQL Workbench
-- Fri Aug  6 15:27:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgi_ceb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgi_ceb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `sgi_ceb` DEFAULT CHARACTER SET utf8mb4 ;
USE `sgi_ceb` ;

-- -----------------------------------------------------
-- Table `sgi_ceb`.`ciculares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`ciculares` (
  `id_cicular` TINYINT(10) NOT NULL,
  `circular` TINYBLOB NOT NULL,
  PRIMARY KEY (`id_cicular`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgi_ceb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`estado` (
  `id_estado` TINYINT(10) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgi_ceb`.`jornada_academica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`jornada_academica` (
  `id_jornada_academica` TINYINT(10) NOT NULL,
  `jornada_academica` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  PRIMARY KEY (`id_jornada_academica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgi_ceb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`genero` (
  `id_genero` TINYINT(10) NOT NULL,
  `genero` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgi_ceb`.`grupo_sanguineo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`grupo_sanguineo` (
  `id_grupo_sanguineo` TINYINT(10) NOT NULL,
  `grupo_sanguineo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_grupo_sanguineo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgi_ceb`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`tipo_documento` (
  `id_tipo_documento` TINYINT(10) NOT NULL,
  `tipo_documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgi_ceb`.`tipo_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`tipo_persona` (
  `id_tipo_persona` TINYINT(10) NOT NULL,
  `tipo_persona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgi_ceb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`persona` (
  `num_documento` VARCHAR(25) NOT NULL,
  `primer_nombre` VARCHAR(45) NOT NULL,
  `segundo_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `tipo_documento_id_tipo_documento` TINYINT(10) NOT NULL,
  `tipo_persona_id_tipo_persona` TINYINT(10) NOT NULL,
  `grupo_sanguineo_id_grupo_sanguineo` TINYINT(10) NOT NULL,
  `genero_id_genero` TINYINT(10) NOT NULL,
  `estado_id_estado` TINYINT(10) NOT NULL,
  PRIMARY KEY (`num_documento`, `tipo_documento_id_tipo_documento`),
  INDEX `fk_persona_tipo_persona_idx` (`tipo_persona_id_tipo_persona` ASC) ,
  INDEX `fk_persona_grupo_sanguineo1_idx` (`grupo_sanguineo_id_grupo_sanguineo` ASC) ,
  INDEX `fk_persona_genero1_idx` (`genero_id_genero` ASC) ,
  INDEX `fk_persona_estado1_idx` (`estado_id_estado` ASC) ,
  INDEX `fk_persona_tipo_documento1_idx` (`tipo_documento_id_tipo_documento` ASC) ,
  CONSTRAINT `fk_persona_estado1`
    FOREIGN KEY (`estado_id_estado`)
    REFERENCES `sgi_ceb`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_genero1`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `sgi_ceb`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_grupo_sanguineo1`
    FOREIGN KEY (`grupo_sanguineo_id_grupo_sanguineo`)
    REFERENCES `sgi_ceb`.`grupo_sanguineo` (`id_grupo_sanguineo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_tipo_documento1`
    FOREIGN KEY (`tipo_documento_id_tipo_documento`)
    REFERENCES `sgi_ceb`.`tipo_documento` (`id_tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_tipo_persona`
    FOREIGN KEY (`tipo_persona_id_tipo_persona`)
    REFERENCES `sgi_ceb`.`tipo_persona` (`id_tipo_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgi_ceb`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`estudiante` (
  `id_estudiante` TINYINT(10) NOT NULL,
  `jornada_academica_id_jornada_academica` TINYINT(10) NOT NULL,
  `persona_num_documento` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_estudiante`, `persona_num_documento`),
  INDEX `fk_estudiante_persona1_idx` (`persona_num_documento` ASC) ,
  INDEX `fk_estudiante_jornada_academica1_idx` (`jornada_academica_id_jornada_academica` ASC) ,
  CONSTRAINT `fk_estudiante_jornada_academica1`
    FOREIGN KEY (`jornada_academica_id_jornada_academica`)
    REFERENCES `sgi_ceb`.`jornada_academica` (`id_jornada_academica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_persona1`
    FOREIGN KEY (`persona_num_documento`)
    REFERENCES `sgi_ceb`.`persona` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgi_ceb`.`historial_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`historial_ingreso` (
  `id_historial` TINYINT(10) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `hora_ingreso` TIME NOT NULL,
  `comentario_historial` VARCHAR(60) NULL DEFAULT NULL,
  `persona_num_documento` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_historial`),
  INDEX `fk_historial_ingreso_persona1_idx` (`persona_num_documento` ASC) ,
  CONSTRAINT `fk_historial_ingreso_persona1`
    FOREIGN KEY (`persona_num_documento`)
    REFERENCES `sgi_ceb`.`persona` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgi_ceb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`rol` (
  `id_rol` TINYINT(10) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgi_ceb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_ceb`.`usuario` (
  `id_usuario` TINYINT(10) NOT NULL,
  `correo_usuario` VARCHAR(45) NOT NULL,
  `clave_usuario` VARCHAR(100) NOT NULL,
  `pin_key` VARCHAR(10) NULL DEFAULT NULL,
  `rol_id_rol` TINYINT(10) NOT NULL,
  `persona_num_documento` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_usuario`, `persona_num_documento`),
  INDEX `fk_usuario_rol1_idx` (`rol_id_rol` ASC) ,
  INDEX `fk_usuario_persona1_idx` (`persona_num_documento` ASC) ,
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_num_documento`)
    REFERENCES `sgi_ceb`.`persona` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `sgi_ceb`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
